#!/bin/bash
########################################################################

#Derived alias
export BKDS_BACKEND="$BKDS_APP/BKDS-BACKEND"
export BKDS_BACKEND_LOGS="$BKDS_BACKEND/BKDS-LOGS"
export BKDS_BACKEND_SHELL="$BKDS_BACKEND/shell"
export BKDS_BACKEND_PYTHON="$BKDS_BACKEND/python"
export BKDS_BACKEND_DATA="$BKDS_BACKEND/data"

export BKDS_CONTENT_GEN="$BKDS_BACKEND/BKDS-CONTENT-GEN"
export BKDS_CONTENT_GEN_SHELL="$BKDS_CONTENT_GEN/shell"
export BKDS_CONTENT_GEN_PYTHON="$BKDS_CONTENT_GEN/python"
export BKDS_CONTENT_GEN_DATA="$BKDS_CONTENT_GEN/data"
export BKDS_CONTENT_GEN_LOGS="$BKDS_CONTENT_GEN/logs"

export BKDS_DESKTOP="$BKDS_APP/BKDS-DESKTOP"
export BKDS_DESKTOP_SHELL="$BKDS_DESKTOP/shell"
export BKDS_DESKTOP_PYTHON="$BKDS_DESKTOP/python"
export BKDS_DESKTOP_DATA="$BKDS_DESKTOP/data"
export BKDS_DESKTOP_LOGS="$BKDS_DESKTOP/logs"
export BKDS_DESKTOP_HTML="$BKDS_DESKTOP/html"

export BKDS_SHARE="$BKDS_APP/BKDS-SHARE"
export BKDS_CHROME_EXT="$BKDS_APP/BKDS-CHROME-EXT"

export BKDS_STARTUP="$BKDS_APP/BKDS-STARTUP"
export BKDS_STARTUP_LOGS="$BKDS_STARTUP/logs"
export BKDS_STARTUP_SHELL="$BKDS_STARTUP/shell"
export BKDS_STARTUP_PYTHON="$BKDS_STARTUP/python"
export BKDS_STARTUP_DATA="$BKDS_STARTUP/data"
##############
# BKDS SECTION
export BKDS_UTIL="$BKDS_APP/BKDS-UTIL"
export BKDS_UTIL_SHELL="$BKDS_UTIL/shell"
export BKDS_UTIL_LOGS="$BKDS_UTIL/logs"
export BKDS_LOGS="$BKDS_UTIL/logs"
export BKDS_UTIL_LOCKS="$BKDS_UTIL/locks"

export BKDS_UTIL_DATA="$BKDS_UTIL/data"
export BKDS_UTIL_PYTHON="$BKDS_UTIL/python"
export BKDS_UTIL_MP3="$BKDS_UTIL_DATA/mp3"

export BKDS_WEB_APP="$BKDS_APP/BKDS-WEB-APP/bkds/web"
export BKDS_WEB_APP_HTML="$BKDS_WEB_APP/html"
export BKDS_WEB_APP_FEEDS="$BKDS_WEB_APP_HTML/feeds"
export BKDS_WEB_APP_FEEDS_META="$BKDS_WEB_APP_FEEDS/meta"
export BKDS_WEB_APP_IMAGE="$BKDS_WEB_APP/image"
export BKDS_SETUP="$BKDS_BACKEND/BKDS-SETUP"

export BKDS_AUTO="$BKDS_BACKEND/BKDS-AUTOMATION-CONFIG"
export BKDS_AUTO_SCHED="$BKDS_AUTO/auto_sched"
export BKDS_AUTO_SCHED_DATA="$BKDS_AUTO_SCHED/data"
export BKDS_AUTO_SCHED_SHELL="$BKDS_AUTO_SCHED/shell"
export BKDS_AUTO_SCHED_PYTHON="$BKDS_AUTO_SCHED/python"
export BKDS_AUTO_SCHED_LOGS="$BKDS_AUTO_SCHED/logs"
export BKDS_AUTO_SCHED_LOCKS="$BKDS_AUTO_SCHED/locks"

export BKDS_REPORTING="$BKDS_AUTO/reporting"
export BKDS_REPORTING_DATA="$BKDS_REPORTING/data"
export BKDS_REPORTING_SHELL="$BKDS_REPORTING/shell"
export BKDS_REPORTING_PYTHON="$BKDS_REPORTING/python"

export BKDS_STATS="$BKDS_REPORTING"
export BKDS_STATS_DATA="$BKDS_STATS/data"
export BKDS_STATS_PYTHON="$BKDS_STATS/python"
export BKDS_STATS_PYTHON="$BKDS_STATS/shell"

export BKDS_MEDIA_AUDIO_CONFIG="$BKDS_AUTO/media_audio_config"
export BKDS_MEDIA_AUDIO_CONFIG_PYTHON="$BKDS_MEDIA_AUDIO_CONFIG/python"
export BKDS_MEDIA_AUDIO_CONFIG_SHELL="$BKDS_MEDIA_AUDIO_CONFIG/shell"

export BKDS_UPDATES="$BKDS_AUTO/updates"
export BKDS_UPDATES_PYTHON="$BKDS_UPDATES/python"
export BKDS_UPDATES_DATA="$BKDS_UPDATES/data"
export BKDS_UPDATES_LOGS="$BKDS_UPDATES/logs"

#BKDS_EXPORT_END
####################